import * as fs from "fs"
import * as path from "path"
import * as readline from "readline"

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
const question = (query: string): Promise<string> =>
  new Promise((resolve) => rl.question(query, resolve))

const ROOT_DIR = process.cwd()
const APP_DIR = path.join(ROOT_DIR, "apps/main")

function deleteFolderRecursive(folderPath: string) {
  if (fs.existsSync(folderPath)) {
    fs.rmSync(folderPath, { recursive: true, force: true })
    console.log(`  - removed ${path.relative(ROOT_DIR, folderPath)}`)
  }
}

function updateJsonFile(filePath: string, updater: (json: any) => any) {
  if (!fs.existsSync(filePath)) return
  const json = JSON.parse(fs.readFileSync(filePath, "utf-8"))
  fs.writeFileSync(filePath, JSON.stringify(updater(json), null, 2) + "\n", "utf-8")
}

function writeFile(filePath: string, content: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, "utf-8")
  console.log(`  - wrote ${path.relative(ROOT_DIR, filePath)}`)
}

// --- Generators (always emit @repo/*; the scope-replace pass rewrites them last) ---

function authConfigFor(provider: string): string {
  if (provider === "Custom API") {
    return `import { createAuth, createMockAuthAdapter } from "@repo/auth-core"
import { createCustomApiAuthAdapter } from "@repo/auth-custom-api"

import { apiClient } from "./api"
import { IS_API_CONFIGURED } from "./env"

// Smart fallback: mock auth with no API base URL (instant demo), real custom
// API the moment one is set. See config/env.ts.
export const auth = createAuth(
  IS_API_CONFIGURED ? createCustomApiAuthAdapter(apiClient) : createMockAuthAdapter(),
)
`
  }
  if (provider === "Supabase") {
    return `import { createAuth } from "@repo/auth-core"
import { createSupabaseAuthAdapter } from "@repo/auth-supabase"

export const auth = createAuth(createSupabaseAuthAdapter())
`
  }
  if (provider === "Firebase") {
    return `import { createAuth } from "@repo/auth-core"
import { createFirebaseAuthAdapter } from "@repo/auth-firebase"

export const auth = createAuth(createFirebaseAuthAdapter())
`
  }
  // None / mock
  return `import { createAuth, createMockAuthAdapter } from "@repo/auth-core"

export const auth = createAuth(createMockAuthAdapter())
`
}

function nextConfigFor(keptAdapter: string | null, includeAdmin: boolean): string {
  const pkgs = ["@repo/types", "@repo/utils", "@repo/api-client", "@repo/crud", "@repo/auth-core"]
  if (keptAdapter) pkgs.push(`@repo/${keptAdapter}`)
  if (includeAdmin) pkgs.push("@repo/admin-ui")
  pkgs.push("@repo/web-ui", "@repo/ui")
  const list = pkgs.map((p) => `    "${p}"`).join(",\n")
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
${list}
  ]
}

module.exports = nextConfig
`
}

function envLocalFor(provider: string, vals: Record<string, string>): string {
  const lines = [
    "# Generated by setup-project. Local environment (gitignored).",
    `NEXT_PUBLIC_AUTH_PROVIDER=${provider}`,
  ]
  if (provider === "Custom API") {
    lines.push("# Blank = zero-backend demo mode (mock auth + mock data).")
    lines.push(`NEXT_PUBLIC_API_BASE_URL=${vals.baseUrl ?? ""}`)
  } else if (provider === "Supabase") {
    lines.push(`NEXT_PUBLIC_SUPABASE_URL=${vals.supabaseUrl ?? ""}`)
    lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${vals.supabaseKey ?? ""}`)
  } else if (provider === "Firebase") {
    lines.push(`NEXT_PUBLIC_FIREBASE_API_KEY=${vals.fbApiKey ?? ""}`)
    lines.push(`NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${vals.fbAuthDomain ?? ""}`)
    lines.push(`NEXT_PUBLIC_FIREBASE_PROJECT_ID=${vals.fbProjectId ?? ""}`)
  }
  return lines.join("\n") + "\n"
}

async function main() {
  console.log("\x1b[36m%s\x1b[0m", "\n=============================================")
  console.log("\x1b[36m%s\x1b[0m", "   Probietech Workspace Setup Command CLI    ")
  console.log("\x1b[36m%s\x1b[0m", "=============================================\n")

  const projectName = (await question("1. Project name (e.g. probietech-app): ")) || "probietech-app"
  const scopeName = (await question("2. Workspace package scope [@repo]: ")) || "@repo"

  console.log("\nChoose Authentication Provider:")
  console.log("  1) Supabase")
  console.log("  2) Firebase")
  console.log("  3) Custom API (default)")
  console.log("  4) None (mock/demo only)")
  const authSelect = (await question("Select option (1-4) [3]: ")) || "3"

  let authProvider = "Custom API"
  if (authSelect === "1") authProvider = "Supabase"
  if (authSelect === "2") authProvider = "Firebase"
  if (authSelect === "4") authProvider = "None"

  // Provider-specific config.
  const vals: Record<string, string> = {}
  if (authProvider === "Custom API") {
    vals.baseUrl = (
      await question("   Custom API base URL (blank = demo mode, e.g. http://localhost:8000): ")
    ).trim()
  } else if (authProvider === "Supabase") {
    vals.supabaseUrl = (await question("   Supabase URL: ")).trim()
    vals.supabaseKey = (await question("   Supabase anon key: ")).trim()
  } else if (authProvider === "Firebase") {
    vals.fbApiKey = (await question("   Firebase API key: ")).trim()
    vals.fbAuthDomain = (await question("   Firebase auth domain: ")).trim()
    vals.fbProjectId = (await question("   Firebase project ID: ")).trim()
  }

  const includeAdmin = ((await question("\n3. Include admin panel? (Y/n): ")) || "y")
    .toLowerCase()
    .startsWith("y")
  const includeWebAuth = ((await question("4. Include web auth pages? (Y/n): ")) || "y")
    .toLowerCase()
    .startsWith("y")
  const useUserModule = ((await question("5. Include example users module? (Y/n): ")) || "y")
    .toLowerCase()
    .startsWith("y")
  const useDashboard = ((await question("6. Include example dashboard widgets? (Y/n): ")) || "y")
    .toLowerCase()
    .startsWith("y")
  const ejectSetup = ((await question("7. Remove setup tooling when done? (Y/n): ")) || "y")
    .toLowerCase()
    .startsWith("y")

  rl.close()
  console.log("\n\x1b[33m%s\x1b[0m", "Configuring workspace...\n")

  const allAuthAdapters = ["auth-supabase", "auth-firebase", "auth-custom-api"]
  const keptAdapter =
    authProvider === "Supabase"
      ? "auth-supabase"
      : authProvider === "Firebase"
        ? "auth-firebase"
        : authProvider === "Custom API"
          ? "auth-custom-api"
          : null

  // The chosen adapter must still exist in this checkout.
  if (keptAdapter && !fs.existsSync(path.join(ROOT_DIR, "packages", keptAdapter))) {
    console.error(
      `\x1b[31mError:\x1b[0m packages/${keptAdapter} is missing. Run setup on a fresh clone of the template.`,
    )
    process.exit(1)
  }

  // --- Prune unused auth adapters ---
  for (const adapter of allAuthAdapters) {
    if (adapter !== keptAdapter) deleteFolderRecursive(path.join(ROOT_DIR, "packages", adapter))
  }

  // --- Prune optional features ---
  if (!includeAdmin) {
    deleteFolderRecursive(path.join(ROOT_DIR, "packages", "admin-ui"))
    deleteFolderRecursive(path.join(APP_DIR, "src/app/admin"))
  } else {
    if (!useUserModule) {
      deleteFolderRecursive(path.join(APP_DIR, "src/modules/users"))
      deleteFolderRecursive(path.join(APP_DIR, "src/app/admin/users"))
    }
    if (!useDashboard) deleteFolderRecursive(path.join(APP_DIR, "src/app/admin/dashboard"))
  }
  if (!includeWebAuth) {
    deleteFolderRecursive(path.join(APP_DIR, "src/app/(web)/login"))
    deleteFolderRecursive(path.join(APP_DIR, "src/app/(web)/register"))
  }

  // --- app dependencies: keep needed adapter (+ crud + auth-core), drop the rest ---
  updateJsonFile(path.join(APP_DIR, "package.json"), (pkg) => {
    for (const adapter of allAuthAdapters) {
      if (adapter !== keptAdapter) delete pkg.dependencies[`@repo/${adapter}`]
    }
    pkg.dependencies["@repo/crud"] = "workspace:*"
    pkg.dependencies["@repo/auth-core"] = "workspace:*"
    if (keptAdapter) pkg.dependencies[`@repo/${keptAdapter}`] = "workspace:*"
    if (!includeAdmin) delete pkg.dependencies["@repo/admin-ui"]
    return pkg
  })
  updateJsonFile(path.join(ROOT_DIR, "apps/storybook/package.json"), (pkg) => {
    if (!includeAdmin && pkg.dependencies) delete pkg.dependencies["@repo/admin-ui"]
    return pkg
  })

  // --- regenerate next.config.js with the correct transpile list (deterministic) ---
  writeFile(path.join(APP_DIR, "next.config.js"), nextConfigFor(keptAdapter, includeAdmin))

  // --- generate auth config ---
  writeFile(path.join(APP_DIR, "src/config/auth.ts"), authConfigFor(authProvider))

  // --- write env (.env.local in apps/main — the location Next actually reads) ---
  writeFile(path.join(APP_DIR, ".env.local"), envLocalFor(authProvider, vals))

  // --- apply chosen package scope across the repo ---
  if (scopeName !== "@repo") {
    console.log(`  - applying scope ${scopeName}`)
    const walk = (dir: string) => {
      for (const item of fs.readdirSync(dir)) {
        if (["node_modules", ".next", ".turbo", ".git"].includes(item)) continue
        const full = path.join(dir, item)
        if (fs.statSync(full).isDirectory()) walk(full)
        else if (/\.(json|ts|tsx|js)$/.test(item)) {
          const content = fs.readFileSync(full, "utf-8")
          if (content.includes("@repo/"))
            fs.writeFileSync(full, content.replace(/@repo\//g, `${scopeName}/`), "utf-8")
        }
      }
    }
    walk(ROOT_DIR)
  }

  // --- root project name (+ optionally eject the one-time setup tooling) ---
  updateJsonFile(path.join(ROOT_DIR, "package.json"), (json) => {
    json.name = projectName
    if (ejectSetup) {
      delete json.scripts?.["setup-project"]
      delete json.devDependencies?.["ts-node"]
    }
    return json
  })
  if (ejectSetup) deleteFolderRecursive(path.join(ROOT_DIR, "scripts/setup-project.ts"))

  console.log("\x1b[32m%s\x1b[0m", "\n✓ Workspace configured.\n")
  console.log("Next steps:")
  console.log("  1. pnpm install        (relink workspace packages)")
  console.log("  2. pnpm dev            (http://localhost:3000)")
  if (authProvider === "Custom API" && !vals.baseUrl) {
    console.log(
      "\n  Running in demo mode (mock auth + data). Set NEXT_PUBLIC_API_BASE_URL in",
    )
    console.log("  apps/main/.env.local to switch to your real API — no code changes needed.")
  }
  console.log("")
}

main().catch((err) => {
  console.error("Error setting up project:", err)
  rl.close()
})
